services:

  inventory-service:
    build:
      context: ..
      dockerfile: sync-REST/inventory_service/Dockerfile
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - microservices-net

  notification-service:
    build:
      context: ..
      dockerfile: sync-REST/notification_service/Dockerfile
    container_name: notification-service
    ports:
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - microservices-net
 
  order-service:
    build:
      context: ..
      dockerfile: sync-REST/order_service/Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - NOTIFICATION_SERVICE_URL=http://notification-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
    depends_on:
      - notification-service
      - inventory-service
    networks:
      - microservices-net

  order-service-tests:
    build:
      context: ..
      dockerfile: sync-REST/tests/Dockerfile
    container_name: order-service-tests
    environment:
      - ORDER_SERVICE_URL=http://order-service:8080
    depends_on:
      - order-service
    networks:
      - microservices-net
    profiles:
      - test

networks:
  microservices-net:
    driver: bridge

## Run all services and tests
# docker-compose --profile test up --build --abort-on-container-exit

# # View results and cleanup
# docker-compose --profile test down